import postgres from "postgres"
import { Kysely, sql } from "kysely"
import { PostgresJSDialect } from "kysely-postgres-js"
import type { Database } from "@openzerg/common/entities/kysely-database"

export type DB = Kysely<Database>

export function openDB(databaseURL: string): DB {
  const pg = postgres(databaseURL)
  return new Kysely<Database>({
    dialect: new PostgresJSDialect({ postgres: pg }),
  })
}

export async function autoMigrate(databaseURL: string): Promise<void> {
  const db = openDB(databaseURL)
  try {
    await db.schema.createTable("registry_instances")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("name", "text", (col) => col.notNull())
      .addColumn("instanceType", "text", (col) => col.notNull())
      .addColumn("ip", "text", (col) => col.notNull())
      .addColumn("port", "integer", (col) => col.notNull())
      .addColumn("publicUrl", "text", (col) => col.notNull())
      .addColumn("lifecycle", "text", (col) => col.notNull().defaultTo("active"))
      .addColumn("lastSeen", "bigint", (col) => col.notNull().defaultTo(0n))
      .addColumn("metadata", "text", (col) => col.notNull().defaultTo("{}"))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createIndex("idx_registry_instances_instanceType")
      .ifNotExists()
      .on("registry_instances")
      .column("instanceType")
      .execute()

    await db.schema.createIndex("idx_registry_instances_lastSeen")
      .ifNotExists()
      .on("registry_instances")
      .column("lastSeen")
      .execute()

    await db.schema.createTable("registry_roles")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("name", "text", (col) => col.notNull().unique())
      .addColumn("description", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("systemPrompt", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("aiProxyId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("zcpServers", "text", (col) => col.notNull().defaultTo("[]"))
      .addColumn("skills", "text", (col) => col.notNull().defaultTo("[]"))
      .addColumn("extraPkgs", "text", (col) => col.notNull().defaultTo("[]"))
      .addColumn("maxSteps", "integer", (col) => col.notNull().defaultTo(50))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createTable("registry_sessions")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("title", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("roleId", "text", (col) => col.notNull())
      .addColumn("workerId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("agentId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("sessionToken", "text", (col) => col.notNull().unique())
      .addColumn("state", "text", (col) => col.notNull().defaultTo("stopped"))
      .addColumn("workspaceId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("inputTokens", "bigint", (col) => col.notNull().defaultTo(0n))
      .addColumn("outputTokens", "bigint", (col) => col.notNull().defaultTo(0n))
      .addColumn("lastActiveAt", "bigint", (col) => col.notNull().defaultTo(0n))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createIndex("idx_registry_sessions_roleId")
      .ifNotExists()
      .on("registry_sessions")
      .column("roleId")
      .execute()

    await db.schema.createIndex("idx_registry_sessions_workerId")
      .ifNotExists()
      .on("registry_sessions")
      .column("workerId")
      .execute()

    await db.schema.createIndex("idx_registry_sessions_agentId")
      .ifNotExists()
      .on("registry_sessions")
      .column("agentId")
      .execute()

    await db.schema.createIndex("idx_registry_sessions_state")
      .ifNotExists()
      .on("registry_sessions")
      .column("state")
      .execute()

    await db.schema.createIndex("idx_registry_sessions_workspaceId")
      .ifNotExists()
      .on("registry_sessions")
      .column("workspaceId")
      .execute()

    await db.schema.createIndex("idx_registry_sessions_createdAt")
      .ifNotExists()
      .on("registry_sessions")
      .column("createdAt")
      .execute()

    await db.schema.createTable("registry_workspaces")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("volumeName", "text", (col) => col.notNull())
      .addColumn("state", "text", (col) => col.notNull().defaultTo("creating"))
      .addColumn("boundSessionId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createIndex("idx_registry_workspaces_state")
      .ifNotExists()
      .on("registry_workspaces")
      .column("state")
      .execute()

    await db.schema.createIndex("idx_registry_workspaces_boundSessionId")
      .ifNotExists()
      .on("registry_workspaces")
      .column("boundSessionId")
      .execute()

    await db.schema.createTable("registry_messages")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("sessionId", "text", (col) => col.notNull())
      .addColumn("role", "text", (col) => col.notNull())
      .addColumn("parentMessageId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("toolCallId", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("toolName", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("content", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("tokenUsage", "text", (col) => col.notNull().defaultTo("{}"))
      .addColumn("metadata", "text", (col) => col.notNull().defaultTo("{}"))
      .addColumn("compacted", "boolean", (col) => col.notNull().defaultTo(false))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createIndex("idx_registry_messages_sessionId")
      .ifNotExists()
      .on("registry_messages")
      .column("sessionId")
      .execute()

    await db.schema.createIndex("idx_registry_messages_session_createdAt")
      .ifNotExists()
      .on("registry_messages")
      .columns(["sessionId", "createdAt"])
      .execute()

    await db.schema.createIndex("idx_registry_messages_session_compacted")
      .ifNotExists()
      .on("registry_messages")
      .columns(["sessionId", "compacted"])
      .execute()

    await db.schema.createTable("registry_workers")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("name", "text", (col) => col.notNull().unique())
      .addColumn("containerName", "text", (col) => col.notNull())
      .addColumn("image", "text", (col) => col.notNull())
      .addColumn("secret", "text", (col) => col.notNull())
      .addColumn("lifecycle", "text", (col) => col.notNull().defaultTo("running"))
      .addColumn("workspaceRoot", "text", (col) => col.notNull().defaultTo("/data/workspace"))
      .addColumn("filesystemUrl", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("executionUrl", "text", (col) => col.notNull().defaultTo(""))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    await db.schema.createIndex("idx_registry_workers_lifecycle")
      .ifNotExists()
      .on("registry_workers")
      .column("lifecycle")
      .execute()

    await db.schema.createTable("registry_skills")
      .ifNotExists()
      .addColumn("id", "text", (col) => col.notNull().primaryKey())
      .addColumn("slug", "text", (col) => col.notNull().unique())
      .addColumn("name", "text", (col) => col.notNull())
      .addColumn("description", "text", (col) => col.notNull())
      .addColumn("gitUrl", "text", (col) => col.notNull())
      .addColumn("localPath", "text", (col) => col.notNull())
      .addColumn("commitHash", "text", (col) => col.notNull())
      .addColumn("pkgs", "text", (col) => col.notNull().defaultTo("[]"))
      .addColumn("createdAt", "bigint", (col) => col.notNull())
      .addColumn("updatedAt", "bigint", (col) => col.notNull())
      .execute()

    console.log("[registry] database ready")
  } finally {
    await db.destroy()
  }
}
